### ISSUE TITLE
Linking with MapKit framework overflows stack with textInputTraitsProperties

### ISSUE THREAD

**Issue by gradha** [domesticcatsoftware/DCIntrospect#25]
This is a very similar issue to the one discussed in #22. To reproduce, open the demo application and link against the MapKit.framework. Build and run. As soon as you try to type into a text field, the recursive bug happens again, this time with a UIFieldInput object. Here's a gdb trace from my own application which I caught setting a breakpoint and waiting for the recursion to happen:

```
(gdb) bt
#0  UITextInputTraits_valueForKey (self=0x6085600, _cmd=0x515edb4, key=0x5c70ce0) at DCIntrospect.m:79
#1  0x0000b421 in UITextInputTraits_valueForKey (self=0x6085600, _cmd=0x515edb4, key=0x5c70ce0) at DCIntrospect.m:87
#2  0x0000b421 in UITextInputTraits_valueForKey (self=0x6085600, _cmd=0x515edb4, key=0x5c70ce0) at DCIntrospect.m:87
#3  0x05cb56bf in -[NSObject(UIAccessibilitySafeCategory) safeValueForKey:] ()
#4  0x05c218f6 in -[UIWebDocumentViewAccessibility(SafeCategory) _accessibilityDocumentView] ()
#5  0x05c2122b in -[UIWebDocumentViewAccessibility(SafeCategory) _accessibilityRootObject] ()
#6  0x05c211ad in -[UIWebDocumentViewAccessibility(SafeCategory) accessibilityElementCount] ()
#7  0x05c191d4 in -[UITextFieldAccessibility(SafeCategory) _accessibilityCountAccessibleChildren:] ()
#8  0x05c19a5c in -[UITextFieldAccessibility(SafeCategory) _updateButtons] ()
#9  0x000ebcab in -[UITextField layoutSubviews] ()
#10 0x00d90a5a in -[CALayer layoutSublayers] ()
#11 0x00d92ddc in CALayerLayoutIfNeeded ()
#12 0x00d380b4 in CA::Context::commit_transaction ()
#13 0x00d39294 in CA::Transaction::commit ()
#14 0x00d3946d in CA::Transaction::observer_callback ()
#15 0x010cf89b in __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ ()
#16 0x010646e7 in __CFRunLoopDoObservers ()
#17 0x0102d1d7 in __CFRunLoopRun ()
#18 0x0102c840 in CFRunLoopRunSpecific ()
#19 0x0102c761 in CFRunLoopRunInMode ()
#20 0x013261c4 in GSEventRunModal ()
#21 0x01326289 in GSEventRun ()
#22 0x0005dc93 in UIApplicationMain ()
#23 0x000027ff in main (argc=1, argv=0xbfffe818) at main.m:6
(gdb) f 2
#2  0x0000b421 in UITextInputTraits_valueForKey (self=0x6085600, _cmd=0x515edb4, key=0x5c70ce0) at DCIntrospect.m:87
87          return valueForKey(self, _cmd, key);
(gdb) po key
_webView
(gdb) po _cmd
0x515edb4 does not appear to point to a valid object.
(gdb) po self
<UIFieldEditor: 0x6085600; frame = (0 0; 173 28); text = ''; opaque = NO; layer = <UIWebLayer: 0xac21c00>>
(gdb) 
```

Presumably the swizzling trick that was done for UITextField has to be done for the undocumented/private UIFieldEditor, but I don't know how to do that. Any help?

**Comment by 0xced** [comment]
Are you using the latest version of DCIntrospect? I can't reproduce this bug here. I linked with MapKit, added a MKMapView to the demo app, started typing in the text field but nothing special happened.

**Comment by gradha** [comment]
Argh! Stupid me. I have two branches on my fork and I was cloning the incorrect one which doesn't contain the change. Sorry! Indeed, the latest version works fine. The next time I'll prepare bug reports against upstream rather than my own fork.
